[global]
log_level = "info"
data_dir = "filefilego_data"
mine = false
mine_keypath = ""
mine_pass = ""
full_text = true

[host]

[rpc]
enabled = true
enabled_services = ["discovery"]
whitelist = ["*"]
    [rpc.socket]
    enabled = true
    path = ""

    [rpc.http]
    enabled = true
    listen_port = 8668
    cross_origin_value = "*"
    listen_address = "localhost"

    [rpc.websocket]
    enabled = true
    listen_port = 8669
    cross_origin_value = "*"
    listen_address = "localhost"
       
[p2p]
max_peers = 20
listen_port = 10209
connection_timeout = 60
min_peers_threashold = 30
listen_address = "localhost"
    [p2p.bootstraper]
    nodes = []
    bootstrap_periodic = 30