// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockQueryType int32

const (
	BlockQueryType_HEIGHT BlockQueryType = 0
	BlockQueryType_BLOCK  BlockQueryType = 1
)

var BlockQueryType_name = map[int32]string{
	0: "HEIGHT",
	1: "BLOCK",
}

var BlockQueryType_value = map[string]int32{
	"HEIGHT": 0,
	"BLOCK":  1,
}

func (x BlockQueryType) String() string {
	return proto.EnumName(BlockQueryType_name, int32(x))
}

func (BlockQueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type GossipPayload_GossipPayloadType int32

const (
	GossipPayload_BLOCK       GossipPayload_GossipPayloadType = 0
	GossipPayload_TRANSACTION GossipPayload_GossipPayloadType = 1
)

var GossipPayload_GossipPayloadType_name = map[int32]string{
	0: "BLOCK",
	1: "TRANSACTION",
}

var GossipPayload_GossipPayloadType_value = map[string]int32{
	"BLOCK":       0,
	"TRANSACTION": 1,
}

func (x GossipPayload_GossipPayloadType) String() string {
	return proto.EnumName(GossipPayload_GossipPayloadType_name, int32(x))
}

func (GossipPayload_GossipPayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2, 0}
}

type Block struct {
	Timestamp            int64          `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Data                 []byte         `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	PrevBlockHash        []byte         `protobuf:"bytes,3,opt,name=PrevBlockHash,proto3" json:"PrevBlockHash,omitempty"`
	Hash                 []byte         `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            []byte         `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,6,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Nounce               string   `protobuf:"bytes,3,opt,name=Nounce,proto3" json:"Nounce,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	From                 string   `protobuf:"bytes,5,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,6,opt,name=To,proto3" json:"To,omitempty"`
	Value                string   `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	TransactionFees      string   `protobuf:"bytes,8,opt,name=TransactionFees,proto3" json:"TransactionFees,omitempty"`
	Signature            []byte   `protobuf:"bytes,9,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Transaction) GetNounce() string {
	if m != nil {
		return m.Nounce
	}
	return ""
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetTransactionFees() string {
	if m != nil {
		return m.TransactionFees
	}
	return ""
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GossipPayload struct {
	Type                 GossipPayload_GossipPayloadType `protobuf:"varint,1,opt,name=Type,proto3,enum=node.GossipPayload_GossipPayloadType" json:"Type,omitempty"`
	Payload              []byte                          `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GossipPayload) Reset()         { *m = GossipPayload{} }
func (m *GossipPayload) String() string { return proto.CompactTextString(m) }
func (*GossipPayload) ProtoMessage()    {}
func (*GossipPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *GossipPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipPayload.Unmarshal(m, b)
}
func (m *GossipPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipPayload.Marshal(b, m, deterministic)
}
func (m *GossipPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipPayload.Merge(m, src)
}
func (m *GossipPayload) XXX_Size() int {
	return xxx_messageInfo_GossipPayload.Size(m)
}
func (m *GossipPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GossipPayload proto.InternalMessageInfo

func (m *GossipPayload) GetType() GossipPayload_GossipPayloadType {
	if m != nil {
		return m.Type
	}
	return GossipPayload_BLOCK
}

func (m *GossipPayload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BlockQuery struct {
	Type                 BlockQueryType `protobuf:"varint,1,opt,name=Type,proto3,enum=node.BlockQueryType" json:"Type,omitempty"`
	BlockNoFrom          uint64         `protobuf:"varint,2,opt,name=BlockNoFrom,proto3" json:"BlockNoFrom,omitempty"`
	BlockNoTo            uint64         `protobuf:"varint,3,opt,name=BlockNoTo,proto3" json:"BlockNoTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockQuery) Reset()         { *m = BlockQuery{} }
func (m *BlockQuery) String() string { return proto.CompactTextString(m) }
func (*BlockQuery) ProtoMessage()    {}
func (*BlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *BlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockQuery.Unmarshal(m, b)
}
func (m *BlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockQuery.Marshal(b, m, deterministic)
}
func (m *BlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockQuery.Merge(m, src)
}
func (m *BlockQuery) XXX_Size() int {
	return xxx_messageInfo_BlockQuery.Size(m)
}
func (m *BlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BlockQuery proto.InternalMessageInfo

func (m *BlockQuery) GetType() BlockQueryType {
	if m != nil {
		return m.Type
	}
	return BlockQueryType_HEIGHT
}

func (m *BlockQuery) GetBlockNoFrom() uint64 {
	if m != nil {
		return m.BlockNoFrom
	}
	return 0
}

func (m *BlockQuery) GetBlockNoTo() uint64 {
	if m != nil {
		return m.BlockNoTo
	}
	return 0
}

type BlockQueryResponse struct {
	From uint64 `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To   uint64 `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	// bytes Payload = 3;
	Payload              []*Block       `protobuf:"bytes,3,rep,name=Payload,proto3" json:"Payload,omitempty"`
	Error                bool           `protobuf:"varint,4,opt,name=Error,proto3" json:"Error,omitempty"`
	Type                 BlockQueryType `protobuf:"varint,5,opt,name=Type,proto3,enum=node.BlockQueryType" json:"Type,omitempty"`
	NodeHeight           uint64         `protobuf:"varint,6,opt,name=NodeHeight,proto3" json:"NodeHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockQueryResponse) Reset()         { *m = BlockQueryResponse{} }
func (m *BlockQueryResponse) String() string { return proto.CompactTextString(m) }
func (*BlockQueryResponse) ProtoMessage()    {}
func (*BlockQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *BlockQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockQueryResponse.Unmarshal(m, b)
}
func (m *BlockQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockQueryResponse.Marshal(b, m, deterministic)
}
func (m *BlockQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockQueryResponse.Merge(m, src)
}
func (m *BlockQueryResponse) XXX_Size() int {
	return xxx_messageInfo_BlockQueryResponse.Size(m)
}
func (m *BlockQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockQueryResponse proto.InternalMessageInfo

func (m *BlockQueryResponse) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *BlockQueryResponse) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *BlockQueryResponse) GetPayload() []*Block {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BlockQueryResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *BlockQueryResponse) GetType() BlockQueryType {
	if m != nil {
		return m.Type
	}
	return BlockQueryType_HEIGHT
}

func (m *BlockQueryResponse) GetNodeHeight() uint64 {
	if m != nil {
		return m.NodeHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("node.BlockQueryType", BlockQueryType_name, BlockQueryType_value)
	proto.RegisterEnum("node.GossipPayload_GossipPayloadType", GossipPayload_GossipPayloadType_name, GossipPayload_GossipPayloadType_value)
	proto.RegisterType((*Block)(nil), "node.Block")
	proto.RegisterType((*Transaction)(nil), "node.Transaction")
	proto.RegisterType((*GossipPayload)(nil), "node.GossipPayload")
	proto.RegisterType((*BlockQuery)(nil), "node.BlockQuery")
	proto.RegisterType((*BlockQueryResponse)(nil), "node.BlockQueryResponse")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0x86, 0xd9, 0xc4, 0x36, 0x78, 0x0c, 0x21, 0xac, 0x50, 0xe5, 0x03, 0xaa, 0x22, 0xab, 0xa8,
	0x56, 0x0f, 0xa9, 0x44, 0xd5, 0x43, 0x8f, 0x40, 0x81, 0x20, 0x2a, 0x93, 0x2e, 0xab, 0xde, 0x97,
	0x64, 0x15, 0xac, 0x26, 0x5e, 0x6b, 0xd7, 0x46, 0xca, 0x83, 0xf4, 0x79, 0x7a, 0xed, 0x9b, 0xf4,
	0x35, 0x2a, 0x8f, 0x5d, 0x7b, 0x4d, 0x0f, 0xbd, 0xed, 0x7c, 0x33, 0xe3, 0xfd, 0xff, 0x99, 0x35,
	0x8c, 0x36, 0xd2, 0x18, 0xb1, 0x92, 0x66, 0x9a, 0x6b, 0x55, 0x28, 0xea, 0x64, 0x6a, 0x29, 0xa3,
	0x5f, 0x04, 0xdc, 0x8b, 0xb5, 0x5a, 0x7c, 0xa7, 0x27, 0xe0, 0xf3, 0x74, 0x23, 0x4d, 0x21, 0x36,
	0x79, 0x48, 0x26, 0x24, 0x1e, 0xb2, 0x0e, 0x50, 0x0a, 0xce, 0x67, 0x51, 0x88, 0x70, 0x30, 0x21,
	0xf1, 0x3e, 0xc3, 0x33, 0x7d, 0x03, 0x07, 0x73, 0x2d, 0x9f, 0xb1, 0x7d, 0x26, 0xcc, 0x53, 0x38,
	0xc4, 0x64, 0x1f, 0x56, 0x9d, 0x98, 0x74, 0xea, 0x4e, 0x64, 0x27, 0xe0, 0x3f, 0xa4, 0xab, 0x4c,
	0x14, 0xa5, 0x96, 0xa1, 0x8b, 0x89, 0x0e, 0xd0, 0x8f, 0xb0, 0xcf, 0xb5, 0xc8, 0x8c, 0x58, 0x14,
	0xa9, 0xca, 0x4c, 0xe8, 0x4d, 0x86, 0x71, 0x70, 0x76, 0x34, 0xad, 0x04, 0x4f, 0xad, 0x0c, 0xeb,
	0x95, 0x45, 0xbf, 0x09, 0x04, 0x16, 0x68, 0x2f, 0x26, 0xd6, 0xc5, 0xaf, 0xc0, 0x9b, 0x97, 0x8f,
	0x77, 0x72, 0x8b, 0x46, 0x7c, 0xd6, 0x44, 0x15, 0x4f, 0x54, 0x99, 0x2d, 0x24, 0x7a, 0xf0, 0x59,
	0x13, 0xb5, 0xb6, 0x1d, 0xcb, 0x36, 0x05, 0xe7, 0x5a, 0xab, 0x0d, 0xea, 0xf6, 0x19, 0x9e, 0xe9,
	0x08, 0x06, 0x5c, 0x85, 0x1e, 0x92, 0x01, 0x57, 0xf4, 0x18, 0xdc, 0x6f, 0x62, 0x5d, 0xca, 0x70,
	0x17, 0x51, 0x1d, 0xd0, 0x18, 0x0e, 0x2d, 0x81, 0xd7, 0x52, 0x9a, 0x70, 0x0f, 0xf3, 0x2f, 0x71,
	0x7f, 0x40, 0xfe, 0x8b, 0x01, 0x45, 0x3f, 0x08, 0x1c, 0xdc, 0x28, 0x63, 0xd2, 0x7c, 0x2e, 0xb6,
	0x6b, 0x25, 0x96, 0xf4, 0x13, 0x38, 0x7c, 0x9b, 0x4b, 0xf4, 0x3a, 0x3a, 0x3b, 0xad, 0x47, 0xd5,
	0x2b, 0xe9, 0x47, 0x55, 0x31, 0xc3, 0x16, 0x1a, 0xc2, 0x6e, 0x03, 0x9b, 0xe5, 0xfe, 0x0d, 0xa3,
	0xf7, 0x70, 0xf4, 0x4f, 0x13, 0xf5, 0xc1, 0xbd, 0xf8, 0x72, 0x7f, 0x79, 0x37, 0xde, 0xa1, 0x87,
	0x10, 0x70, 0x76, 0x9e, 0x3c, 0x9c, 0x5f, 0xf2, 0xdb, 0xfb, 0x64, 0x4c, 0xa2, 0x67, 0x00, 0xdc,
	0xfb, 0xd7, 0x52, 0xea, 0x2d, 0x8d, 0x7b, 0x9a, 0x8e, 0x6b, 0x4d, 0x5d, 0xde, 0x92, 0x30, 0x81,
	0x00, 0x79, 0xa2, 0x70, 0xb0, 0x95, 0x0c, 0x87, 0xd9, 0xa8, 0x9a, 0x47, 0x13, 0x72, 0x85, 0x2b,
	0x72, 0x58, 0x07, 0xa2, 0x9f, 0x04, 0x68, 0xf7, 0x61, 0x26, 0x4d, 0xae, 0x32, 0x23, 0xdb, 0x45,
	0x11, 0xac, 0xb7, 0x17, 0x55, 0xdf, 0x50, 0x2d, 0xea, 0xb4, 0x73, 0x3f, 0xc4, 0x67, 0x16, 0x58,
	0x3a, 0xdb, 0x51, 0x54, 0xfb, 0xbc, 0xd2, 0x5a, 0x69, 0x7c, 0x08, 0x7b, 0xac, 0x0e, 0x5a, 0x87,
	0xee, 0x7f, 0x1d, 0xbe, 0x06, 0x48, 0xd4, 0x52, 0xce, 0x64, 0xba, 0x7a, 0x2a, 0xf0, 0x9d, 0x38,
	0xcc, 0x22, 0xef, 0xde, 0xc2, 0xa8, 0xdf, 0x47, 0x01, 0xbc, 0xd9, 0xd5, 0xed, 0xcd, 0x8c, 0x8f,
	0x77, 0xba, 0x99, 0x93, 0x47, 0x0f, 0x7f, 0xde, 0x0f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x0b, 0xa9, 0x75, 0xce, 0x03, 0x00, 0x00,
}
